name: build sulfur

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc python3

    - name: build files
      run: |
        make linux_one_file
        mv build/sulfur sulfur-onefile-linux-x86_64.elf

        make linux
        mv build/sulfur sulfur-linux-x86_64.elf
        zip -r libs-linux-x86_64.zip build/libs

        make profan
        mv build/sulfur.bin sulfur-profanOS-i386.bin

    - name: Release to GitHub
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: ivra latest runtime
        automatic_release_tag: latest
        repo_token: "${{ secrets.GIT_TOKEN }}"
        files: |
          sulfur-onefile-linux-x86_64.elf
          sulfur-linux-x86_64.elf
          libs-linux-x86_64.zip
          sulfur-profanOS-i386.bin
